services:
  backend:
    build: ./backend
    volumes:
      - backend-data:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TZ=UTC
      - ALLOWED_ORIGINS=http://34.182.55.193,https://service-server.jiwamu.de

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    environment:
      - TZ=UTC

networks:
  default:
    driver: bridge

volumes:
  backend-data:
